export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'
export const USER_CHATS_STATE_CHANGE = 'USER_CHATS_STATE_CHANGE'

export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_LIKES_STATE_CHANGE = 'USERS_LIKES_STATE_CHANGE'
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE'

export const USER_FRIENDS_REQUESTS_SENT_STATE_CHANGE = 'USER_FRIDENDS_REQUESTS_SENT_STATE_CHANGE'
export const USER_FRIENDS_REQUESTS_RECEIVED_STATE_CHANGE = 'USER_FRIDENDS_REQUESTS_RECEIVED_STATE_CHANGE'
export const USER_FRIENDS_STATE_CHANGE = 'USER_FRIDENDS_STATE_CHANGE'

export const USER_CLEAR_FRIENDS = 'USER_CLEAR_FRIENDS'


export const CLEAR_DATA = 'CLEAR_DATA'



